name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ AKIDQaT6i392IHyTqPLIZZIrTpvlT8ZkvHdh}}
        SECRET_KEY: ${{ xmVyuZdPxEEG1ygGetrYyA8rTHq778vW }}
        BUCKET: blog-1251208262
        REGION: ap-beijing
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Build project
      run: yarn && yarn build
    - name: Upload
      run: coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
